---
title: "Свойства зависимых величин. Математическое ожидание и дисперсия. Точность оценки. Задание 4"
author: "Золотиков У. Е."
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

## Оценка ошибки по выборке

```{r samples}
# Функция для оценки ошибки при разном количестве пациентов
evaluate_error <- function(n_patients, p_true, n_repeats) {
  df_all_repeats <- data.frame(
    n_exp = rep(1:n_repeats, each = n_patients),
    ID =  rep(1:n_patients, n_repeats),
    outcome = rbinom(n_repeats * n_patients, 1, p_true)
  )

  df_sample_prob <- df_all_repeats %>%
    group_by(n_exp) %>%
    summarise(mean_outcome = mean(outcome)) %>%
    ungroup()
  
  error <- sqrt(mean((df_sample_prob$mean_outcome - p_true)^2))
  return(error)
}
```

```{r}
sample_sizes <- seq(5, 100, by = 5)
errors <- sapply(sample_sizes, function(n) evaluate_error(n, p_true=0.7, n_repeats=1000))

# Строим график зависимости ошибки от объема выборки
error_df <- data.frame(sample_size = sample_sizes, error = errors)

ggplot(error_df, aes(x = sample_size, y = error)) +
  geom_line() +
  geom_point() +
  theme_bw() +
  labs(title = "Ошибка оценки вероятности в зависимости от объема выборки",
       subtitle = "Эксперимент с оценкой вероятности полного исцеления пациента после приёма препарата",
       x = "Размер выборки",
       y = "Средняя квадратичная ошибка (RMSE)")
```

Видно, что чем больше выборка, тем меньше среднеквадратичная ошибка. Зависимость обратно логарифмическая

## Оценка ошибки по истинной вероятности

```{r p_true}
# Функция для оценки ошибки при разном количестве пациентов
evaluate_error <- function(n_patients, p_true, n_repeats) {
  df_all_repeats <- data.frame(
    n_exp = rep(1:n_repeats, each = n_patients),
    ID =  rep(1:n_patients, n_repeats),
    outcome = rbinom(n_repeats * n_patients, 1, p_true)
  )

  df_sample_prob <- df_all_repeats %>%
    group_by(n_exp) %>%
    summarise(mean_outcome = mean(outcome)) %>%
    ungroup()
  
  error <- sqrt(mean((df_sample_prob$mean_outcome - p_true)^2))
  return(error)
}
```

```{r}
p_true <- seq(0, 1, by = 0.05)
errors <- sapply(p_true, function(n) evaluate_error(n_patients=100, p_true=n, n_repeats=1000))

# Строим график зависимости ошибки от объема выборки
error_df <- data.frame(p_true = p_true, error = errors)

ggplot(error_df, aes(x = p_true, y = error)) +
  geom_line() +
  geom_point() +
  theme_bw() +
  labs(title = "Ошибка оценки вероятности в зависимости её истинного значения",
       subtitle = "Эксперимент с оценкой вероятности полного исцеления пациента после приёма препарата",
       x = "Вероятность",
       y = "Средняя квадратичная ошибка (RMSE)")
```

Видно, что чем ближе вероятность к 0.5, тем выше ошибка, чем ближе к 0 или 1 - тем меньше. Можно предположить, что точность определения события в зоне 0.5 ниже, так как событие ближе к "рандомному".