---
title: "Введение в автоматизацию обработки данных в R"
subtitle: "BioStat 2024"
author: "Ustin Zolotikov"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  toc: yes
  toc_depth: 3
toc-title: "Оглавление"
---

```{r}
library(tidyverse)
library(flextable)
knitr::opts_chunk$set()
```

# Чтение данных

```{bash include=FALSE}
if [ ! -f data_tsv.tsv ]; then wget https://stepik.org/media/attachments/course/122402/data_tsv.tsv; fi
```
```{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
rmarkdown::paged_table(read_tsv("data_tsv.tsv"))
```
# Базовые статистики

```{r}
rds <- read_rds('https://stepik.org/media/attachments/lesson/790859/numeric_data.rds')
dsc <- psych::describe(rds) %>% round(2)
rmarkdown::paged_table(dsc)
```

# Серьезная работа с DataFrame'ами

```{r}
data <- read_tsv('https://stepik.org/media/attachments/lesson/790863/data_tsv.tsv')
data
```
```{r}
data %>% 
  select(`Группа`, where(is.numeric)) %>% 
  group_by(`Группа`) %>% 
  summarize(across(where(is.numeric), function(x) mean(x, na.rm=T))) %>% 
  flextable() %>% 
  theme_box() %>% 
  align(align='center', part='all') %>% 
  bold(j = 1) %>% 
  italic(j = 2:length(.))
```

